import 'package:toplife/main_systems/system_shop_and_storage/constants/food_lifespan.dart';
import 'package:toplife/main_systems/system_shop_and_storage/constants/food_type.dart';
import 'package:toplife/main_systems/system_shop_and_storage/domain/model/food.dart';
import 'package:toplife/main_systems/system_shop_and_storage/shop_info/food/constants/food_names.dart';

Set<Food> ingredients = {
  Food(
    name: FoodNames.mango,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.peas,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.apple,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.blueberry,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.pear,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.banana,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.avocado,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.broccoli,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.spinach,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.sweetPotato,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.oat,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.bread,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 4,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.milk,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 1,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.peanutButter,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 4,
    isOrganic: true,
  ),
   Food(
    name: FoodNames.jelly,
    type: FoodType.ingredient.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 5,
    servings: 4,
    isOrganic: true,
  ),
};
