import 'package:toplife/core/data_source/database_constants.dart';
import 'package:toplife/main_systems/system_shop_and_storage/constants/food_lifespan.dart';
import 'package:toplife/main_systems/system_shop_and_storage/constants/food_type.dart';
import 'package:toplife/core/data_source/drift_database/database_provider.dart';
import 'package:toplife/main_systems/system_shop_and_storage/shop_info/food/constants/food_names.dart';

Set<Food> readyMeals = {
  //nutrition -> low: 1-15, mid: 16-30, high: 31-50
  //lifespan -> only short & mid lifespans. high is reserved for cooked meals

  //low price
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.waffles,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 15,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.salad,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),

  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.hamburger,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.veggieBurger,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.sweetPotatoFries,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 10,
    servings: 1,
    isOrganic: false,
  ),

  //mid price
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.pizza,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 10,
    servings: 8,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.tacos,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 15,
    servings: 2,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.veggieTacos,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 15,
    servings: 2,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.quesadilla,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.baugette,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 15,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.ramen,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 25,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.misoSoup,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.short.days,
    nutrition: 15,
    servings: 1,
    isOrganic: false,
  ),

  //high price
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.spaghettiAndMeatballs,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 30,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.ravioli,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.fettuccineAlfredo,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 25,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.gnocchi,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 20,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.churrasco,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 30,
    servings: 4,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.bibimbap,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 25,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.padThai,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 25,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.sushi,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 30,
    servings: 2,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.jollofRiceAndChicken,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 30,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.veggieFriedRice,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 25,
    servings: 1,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.friedChicken,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 30,
    servings: 4,
    isOrganic: false,
  ),
  Food(
    id: DatabaseConstants.dummyId,
    name: FoodNames.seafoodPlatter,
    type: FoodType.readyMeal.name,
    basePrice: 0,
    lifespanInDays: FoodLifespan.mid.days,
    nutrition: 40,
    servings: 4,
    isOrganic: false,
  ),
};
