import 'dart:math';

String getRandomSchoolName() {
  final schoolNamesList = [
    "Bear River",
    "Big Valley",
    "Broad River",
    "Canyon View",
    "Central",
    "Central Valley",
    "Central Valley",
    "Columbus",
    "Coral Coast",
    "Deer River",
    "Desert Winds",
    "Eastview",
    "Eureka",
    "Forest Lake",
    "Frozen Lake",
    "Granite Hills",
    "Greenville",
    "Hillview",
    "Laguna Bay",
    "Maple Ridge",
    "Marie Curie",
    "Monarch",
    "Oak Park",
    "Oakleaf",
    "Redlands",
    "River Fork",
    "Riverbank",
    "Saint Helena",
    "Seal Bay",
    "Seal Bay",
    "Seaside",
    "Sierra",
    "Stonewall",
    "Summers",
    "Summerville",
    "Sunny Coast",
    "Timber Creek",
    "Vista",
    "Waterfalls",
    "Westwood",
    "Willow",
  ];
  return schoolNamesList
      .elementAt(Random().nextInt(schoolNamesList.length));
}
