import 'dart:math';

import 'package:toplife/main_systems/system_location/countries/country.dart';

String getPersonNameTattooDecription({
  required Country country,
}) {
  final List<Set<String>> nameOptions = [
    country.maleFirstNames,
    country.femaleFirstNames,
    celebrityNames,
    animeCharacterNames,
    superheroNames,
  ];

  //choose a random set from options
  final Set<String> chosenNameSet =
      nameOptions[Random().nextInt(nameOptions.length)];

  //choose a random name from the chosen option
  final String chosenName =
      chosenNameSet.elementAt(Random().nextInt(chosenNameSet.length));

  return chosenName;
}

const Set<String> celebrityNames = {
  "Brad Pitt",
  "Angelina Jolie",
  "Tom Cruise",
  "Jennifer Aniston",
  "Leonardo DiCaprio",
  "Scarlett Johansson",
  "Robert Downey Jr.",
  "Charlize Theron",
  "George Clooney",
  "Sandra Bullock",
  "Johnny Depp",
  "Meryl Streep",
  "Denzel Washington",
  "Julia Roberts",
  "Chris Hemsworth",
  "Emma Stone",
  "Dwayne Johnson (The Rock)",
  "Jennifer Lawrence",
  "Ryan Reynolds",
  "Nicole Kidman",
  "Will Smith",
  "Anne Hathaway",
  "Matt Damon",
  "Natalie Portman",
  "Chris Evans",
  "Emma Watson",
  "Mark Wahlberg",
  "Cate Blanchett",
  "Hugh Jackman",
  "Penélope Cruz",
  "Jamie Foxx",
  "Reese Witherspoon",
  "Benedict Cumberbatch",
  "Kate Winslet",
  "Jason Momoa",
  "Gal Gadot",
  "Idris Elba",
  "Gwyneth Paltrow",
  "Ryan Gosling",
  "Sandra Oh",
  "Keanu Reeves",
  "Viola Davis",
  "Chris Pratt",
  "Halle Berry",
  "Jake Gyllenhaal",
  "Keira Knightley",
  "Eddie Redmayne",
  "Mahershala Ali",
  "Margot Robbie",
  "Jennifer Lopez",
  "Tom Hanks",
  "Beyoncé",
  "Kanye West",
  "Adele",
  "Rihanna",
  "Taylor Swift",
  "Justin Bieber",
  "Selena Gomez",
  "Lady Gaga",
  "Katy Perry",
  "Drake",
  "Kim Kardashian",
  "Eminem",
  "Jay-Z",
  "Justin Timberlake",
  "Britney Spears",
  "Ariana Grande",
  "Demi Lovato",
  "Miley Cyrus",
  "Nicki Minaj",
  "Shawn Mendes",
  "Ed Sheeran",
  "Bruno Mars",
  "Chris Brown",
  "John Legend",
  "Alicia Keys",
  "Usher",
  "Snoop Dogg",
  "Jennifer Hudson",
  "Christina Aguilera",
  "Mariah Carey",
  "Gwen Stefani",
  "Adam Levine",
  "Pharrell Williams",
  "Pink",
  "Kelly Clarkson",
  "Carrie Underwood",
  "Adam Lambert",
  "Camila Cabello",
  "Cardi B",
  "Harry Styles",
  "Halsey",
  "Khalid",
  "Lana Del Rey",
  "Lewis Capaldi",
  "Lizzo",
  "Luke Bryan",
  "Megan Thee Stallion",
  "Niall Horan",
  "Post Malone",
  "Sam Smith",
  "The Weeknd",
  "Billie Eilish",
  "BTS",
  "BLACKPINK",
  "EXO",
  "Hailey Bieber",
  "Tom Holland",
  "Elizabeth Olsen",
  "Zendaya",
  "Robert Pattinson",
  "Millie Bobby Brown",
  "Noah Centineo",
  "Sophie Turner",
  "Maisie Williams",
  "Kit Harington",
  "Emilia Clarke",
  "Nikolaj Coster-Waldau",
  "Peter Dinklage",
  "Tom Hardy",
  "Daniel Radcliffe",
};

const Set<String> animeCharacterNames = {
  "Goku (Dragon Ball series)",
  "Naruto Uzumaki (Naruto series)",
  "Monkey D. Luffy (One Piece)",
  "Light Yagami (Death Note)",
  "Ichigo Kurosaki (Bleach)",
  "Edward Elric (Fullmetal Alchemist)",
  "Levi Ackerman (Attack on Titan)",
  "Sasuke Uchiha (Naruto series)",
  "Vegeta (Dragon Ball series)",
  "Lelouch Lamperouge (Code Geass)",
  "Eren Yeager (Attack on Titan)",
  "Saitama (One Punch Man)",
  "Hinata Hyuga (Naruto series)",
  "Mikasa Ackerman (Attack on Titan)",
  "Ryuk (Death Note)",
  "Natsu Dragneel (Fairy Tail)",
  "Spike Spiegel (Cowboy Bebop)",
  "Kaneki Ken (Tokyo Ghoul)",
  "Gon Freecss (Hunter x Hunter)",
  "Roronoa Zoro (One Piece)",
  "Usui Takumi (Kaichou wa Maid-sama!)",
  "Goku Black (Dragon Ball Super)",
  "Himura Kenshin (Rurouni Kenshin)",
  "Alucard (Hellsing)",
  "Itachi Uchiha (Naruto series)",
  "Jotaro Kujo (JoJo's Bizarre Adventure)",
  "Roy Mustang (Fullmetal Alchemist)",
  "Killua Zoldyck (Hunter x Hunter)",
  "Sesshomaru (Inuyasha)",
  "Rem (Re:Zero)",
  "Eren Jaeger (Attack on Titan)",
  "Kirito (Sword Art Online)",
  "Yuno Gasai (Future Diary)",
  "Akame (Akame ga Kill!)",
  "Zero Kiryu (Vampire Knight)",
  "Holo (Spice and Wolf)",
  "C.C. (Code Geass)",
  "Izuku Midoriya (My Hero Academia)",
  "Shinji Ikari (Neon Genesis Evangelion)",
  "Shoto Todoroki (My Hero Academia)",
  "Hatake Kakashi (Naruto series)",
  "Yagami Light (Death Note)",
  "Mikoto Misaka (A Certain Scientific Railgun)",
  "Rukia Kuchiki (Bleach)",
  "Asuna Yuuki (Sword Art Online)",
  "Haruhi Suzumiya (The Melancholy of Haruhi Suzumiya)",
  "Trafalgar Law (One Piece)",
  "Levi (Attack on Titan)",
  "Todoroki Shoto (My Hero Academia)",
  "Josuke Higashikata (JoJo's Bizarre Adventure: Diamond is Unbreakable)",
  "Ken Kaneki (Tokyo Ghoul)",
  "Erza Scarlet (Fairy Tail)",
  "Gintoki Sakata (Gintama)",
  "Luffy Monkey D. (One Piece)",
  "Shigeo Kageyama (Mob Psycho 100)",
  "Yuu Otosaka (Charlotte)",
  "Ciel Phantomhive (Black Butler)",
  "Koro-sensei (Assassination Classroom)",
  "Sebastian Michaelis (Black Butler)",
  "Rintarou Okabe (Steins;Gate)",
  "Maka Albarn (Soul Eater)",
  "Shoyo Hinata (Haikyuu!!)",
  "Kiritsugu Emiya (Fate/Zero)",
  "Shinobu Oshino (Monogatari series)",
  "Riza Hawkeye (Fullmetal Alchemist: Brotherhood)",
  "Senku Ishigami (Dr. Stone)",
  "Saber (Fate/stay night)",
  "Edward Elric (Fullmetal Alchemist: Brotherhood)",
  "Megumin (KonoSuba)",
  "Ryuko Matoi (Kill la Kill)",
  "Violet Evergarden (Violet Evergarden)",
  "Kanade Tachibana (Angel Beats!)",
  "Guts (Berserk)",
  "Taiga Aisaka (Toradora!)",
  "Katsuki Bakugo (My Hero Academia)",
  "Rin Tohsaka (Fate/stay night)",
  "Hinata Shoyo (Haikyuu!!)",
  "Yato (Noragami)",
  "Yukihira Soma (Food Wars!)",
  "Nezuko Kamado (Demon Slayer: Kimetsu no Yaiba)",
  "Tetsuya Kuroko (Kuroko's Basketball)",
  "Alphonse Elric (Fullmetal Alchemist: Brotherhood)",
  "Lelouch vi Britannia (Code Geass)",
  "Subaru Natsuki (Re:Zero)",
  "Mio Akiyama (K-On!)",
  "Yugi Muto (Yu-Gi-Oh!)",
  "Shota Aizawa (My Hero Academia)",
  "Rikka Takanashi (Love, Chunibyo & Other Delusions)",
  "Hange Zoe (Attack on Titan)",
  "Akatsuki (Log Horizon)",
  "Soma Yukihira (Food Wars!)",
};

const Set<String> superheroNames = {
  "Superman",
  "Batman",
  "Spider-Man",
  "Iron Man",
  "Captain America",
  "Wonder Woman",
  "Thor",
  "Hulk",
  "Black Widow",
  "Wolverine",
  "Deadpool",
  "Aquaman",
  "The Flash",
  "Green Lantern",
  "Black Panther",
  "Doctor Strange",
  "Hawkeye",
  "Captain Marvel",
  "Ant-Man",
  "Scarlet Witch",
  "Storm",
  "Cyclops",
  "Jean Grey (Phoenix)",
  "Nightcrawler",
  "Rogue",
  "Beast",
  "Iceman",
  "Silver Surfer",
  "Daredevil",
  "Ghost Rider",
  "Punisher",
  "Green Arrow",
  "Supergirl",
  "Batgirl",
  "Martian Manhunter",
  "Shazam",
  "Black Canary",
  "Catwoman",
  "Hawkgirl",
  "Robin",
  "Batwoman",
  "Green Hornet",
  "Atom",
  "Power Girl",
  "Blue Beetle",
  "Red Hood",
  "Firestorm",
  "Vixen",
  "Zatanna",
  "Doctor Fate",
  "Hawkman",
  "Constantine",
  "Spawn",
  "Starfire",
  "Raven",
  "Cyborg",
  "Static Shock",
  "Mister Fantastic",
  "Invisible Woman",
  "Human Torch",
  "Thing",
  "Black Bolt",
  "Medusa",
  "Captain Britain",
  "Blade",
  "Luke Cage",
  "Iron Fist",
  "Jessica Jones",
  "Moon Knight",
  "Sentry",
  "Ghost-Spider",
  "Domino",
  "Doctor Doom",
  "Professor X",
  "Magneto",
  "Jean Grey (Marvel Girl)",
  "Cable",
  "Psylocke",
  "Gambit",
  "Elektra",
  "Jessica Drew (Spider-Woman)",
  "Mockingbird",
  "Moonstar",
  "She-Hulk",
  "Wasp",
  "Valkyrie",
  "Jessica Cruz (Green Lantern)",
  "Animal Man",
  "Black Lightning",
  "Green Lantern (John Stewart)",
  "Elongated Man",
  "Fire",
  "Ice",
  "Phantom Stranger",
  "Zatara",
  "Adam Warlock",
  "Ironheart",
  "Firestar",
  "Bumblebee",
};
