import 'package:flutter_test/flutter_test.dart';
import 'package:toplife/core/data_source/drift_database/database_provider.dart';
import 'package:toplife/main_systems/system_relationship/constants/informal_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/inlaw_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/domain/model/info_models/relationship_pair.dart';
import 'package:toplife/main_systems/system_relationship/util/rearrange_inlaws_list.dart';

void main() {
  group("rearrangeInLawsList:", () {
    test(
        "given a list of in laws in order sibling -> parent -> child they will be rearranged in the order parent -> child -> sibling",
        () {
      List<RelationshipPair<InLaw>> givenInLawsList = [
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.sibling.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.parent.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.child.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
      ];

      final List<RelationshipPair<InLaw>> correctInLawsList = [
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.parent.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.child.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
        RelationshipPair(
          relationship: InLaw(
            mainPersonId: 1,
            inLawId: 2,
            likesMainPerson: true,
            inLawRelationshipType: InLawRelationshipType.sibling.name,
            relationship: 89,
            haveRomanticRelationship: false,
            interestedInRelationship: true,
          ),
          person: const Person(
            id: 1,
            gameId: 2,
            hasDriversLicense: false,
            firstName: "Janet",
            lastName: "Johnson",
            dayOfBirth: 34,
            gender: "gender",
            subjectPronoun: "subjectPronoun",
            objectPronoun: "objectPronoun",
            possessivePronoun: "possessivePronoun",
            sexuality: "sexuality",
            birthState: "Ontario",
            birthCountry: "Canada",
            currentState: "Ontario",
            currentCountry: "Canada",
            money: 120,
            zodiacSign: "zodiacSign",
            transportMode: "bus",
            hasFertilityIssues: true,
            onBirthControl: false,
            isSterile: false,
            sickly: true,
            dead: false,
          ),
          informalRelationshipType: InformalRelationshipType.inLaw,
        ),
      ];

      final List<RelationshipPair<InLaw>> resultInLawsList =
          rearrangeInLawsList(givenInLawsList);

      expect(resultInLawsList[0], correctInLawsList[0],
          reason: "Cause: index 0");
      expect(resultInLawsList[1], correctInLawsList[1],
          reason: "Cause: index 1");
      expect(resultInLawsList[2], correctInLawsList[2],
          reason: "Cause: index 2");
    });
  });
}
