import 'dart:math';

String getRandomAddress() {
  //get a random house number btw 100-900
  final int houseNumber = Random().nextInt(800) + 100;

  //get a random index for the list
  final int randomIndex = Random().nextInt(streetNames.length);

  //build the address
  final String address = "$houseNumber ${streetNames[randomIndex]}";

  return address;
}

List<String> streetNames = [
  "3rd Street West",
  "Briarwood Court",
  "Atlantic Avenue",
  "Main Street West",
  "River Road",
  "Hawthorne Avenue",
  "Chicken Dinner Road",
  "Route 7",
  "Central Avenue",
  "Prospect Avenue",
  "Liberty Street",
  "Route 27",
  "Surrey Lane",
  "Cedar Court",
  "Country Club Drive",
  "Route 10",
  "5th Street",
  "West Street",
  "8th Avenue",
  "King Street",
  "Park Street",
  "Chapel Street",
  "Street Road",
  "Circle Drive",
  "Water Street",
  "2nd Street West",
  "Hickory Lane",
  "Schoolhouse Lane",
  "12th Street East",
  "Amherst Street",
  "Pleasant Street",
  "Buckingham Drive",
  "Chestnut Avenue",
  "Adams Avenue",
  "Somerset Drive",
  "Laurel Lane",
  "Front Street",
  "Parker Street",
  "Henry Street",
  "Route 41",
  "River Street",
  "5th Avenue",
  "Race Street",
  "Maple Avenue",
  "Woodland Road",
  "B Street",
  "Hartford Road",
  "Woodland Drive",
  "Maiden Lane",
  "Tanglewood Drive",
  "Clinton Street",
  "Berkshire Drive",
  "Ann Street",
  "5th Street East",
  "Clark Street",
  "Elm Street",
  "Fuk Hing Lane",
  "Route 17",
  "Grove Avenue",
  "Laurel Street",
  "Ivy Lane",
  "Lafayette Street",
  "Lexington Drive",
  "Redwood Drive",
  "Market Street",
  "Spring Street",
  "Penn Street",
  "Harrison Avenue",
  "Cypress Court",
  "Cobblestone Court",
  "Franklin Street",
  "New Street",
  "Railroad Street",
  "Warren Street",
  "Park Place",
  "North Avenue",
  "Beech Street",
  "Edgewood Road",
  "Sheffield Drive",
  "Aspen Drive",
  "Eagle Road",
  "Canal Street",
  "Broad Street",
  "Depot Street",
  "Magnolia Drive",
  "Forest Avenue",
  "Lexington Court",
  "Hooker Street",
  "Manor Drive",
  "Fairview Avenue",
  "South Street",
  "Dogwood Drive",
  "Washington Avenue",
  "East Avenue",
  "Linden Street",
  "Haviture Way",
  "Mulberry Lane",
  "John Street",
  "Grove Street",
  "College Street",
  "Main Street South",
  "Hillcrest Drive",
  "Ridge Avenue",
  "Canterbury Court",
];
