import 'dart:math';

String getThingNameTattooDescription() {
  final List<Set<String>> thingsOptions = [
    randomThings,
    celestialThings,
    zodiacSigns,
    planets,
    tarotCardDeck,
    witchThings,
    flowers,
    plants,
    mythology,
    animals,
  ];

  //choose a random set from options
  final Set<String> chosenThingSet =
      thingsOptions[Random().nextInt(thingsOptions.length)];

  //choose a random name from the chosen option
  final String chosenThing =
      chosenThingSet.elementAt(Random().nextInt(chosenThingSet.length));

  return chosenThing;
}

const Set<String> randomThings = {
  "A Vintage camera",
  "An Hourglass",
  "A Key",
  "A Compass",
  "A Feather",
  "An Anchor",
  "A Rose",
  "A Book",
  "A Tree",
  "A Lantern",
  "A Pocket watch",
  "Music notes",
  "A Quill pen",
  "A Bicycle",
  "Moon phases",
  "A Globe",
  "A Skull",
  "A Butterfly",
  "An Arrow",
  "A Star",
  "A Heart",
  "A Dreamcatcher",
  "A Diamond",
  "Scissors",
  "A Teacup",
  "A Puzzle piece",
  "A Sailing ship",
  "A Chess piece",
  "A Balloon",
  "A Skull and crossbones",
  "An Antique key",
  "A Compass rose",
  "A Feather quill",
  "A Vintage microphone",
  "An Hourglass with wings",
  "An Anchor with rope",
  "A Lotus flower",
  "A Tree of life",
  "A Vintage radio",
  "A Vintage typewriter",
  "A Feather with birds in flight",
  "A Mandala",
  "A Vintage car",
  "A Rose with thorns",
  "A Vintage pocket watch with roses",
  "A Chessboard with pieces",
  "An Old-fashioned telephone",
  "A Vintage sewing machine",
  "A Film reel",
  "A Vintage airplane",
  "A Paintbrush and palette",
  "An Antique keyhole",
  "Geometric shapes (e.g., hexagon, triangle)",
  "An Old-fashioned lantern with flames",
  "A Compass with a map",
  "An Antique telescope",
  "A Vintage globe with coordinates",
  "A Vintage carousel horse",
  "A Vintage camera with film strip",
  "An Antique pocket watch with gears",
  "A Quill pen and inkwell",
  "An Old-fashioned keyhole with ornate details",
  "A Vintage telephone booth",
  "An Hourglass with intricate sand design",
  "A Vintage compass with a detailed map",
  "A Retro boombox with cassette tapes",
  "An Antique book with a lock and key",
  "A Classic film projector",
  "A Vintage radio microphone",
  "An Antique pocket knife",
  "A Vintage bicycle with flowers in the basket",
  "A Retro television set",
  "A Gramophone with musical notes",
  "A Vintage teapot and teacup set",
  "A Vintage suitcase with travel stamps",
  "A Classic jukebox with vinyl records",
  "Steampunk goggles",
  "A Vintage sewing machine with intricate details",
  "An Antique spectacles with a delicate chain",
  "A Vintage oil lamp",
  "A Retro video game console",
  "A Vintage typewriter with flying paper sheets",
  "An Antique globe with detailed continents",
  "A Vintage scales of justice",
  "A Classic rotary dial telephone",
  "A Vintage trinket box with ornate carvings",
  "A Retro surfboard with vibrant patterns",
  "A Classic fountain pen with flowing ink",
};

const Set<String> celestialThings = {
  "Stars",
  "Moons",
  "Sun",
  "Planets",
  "Nebulas",
  "Comets",
  "Asteroids",
  "Meteors",
  "Zodiac constellations",
  "Galaxies",
  "Supernovas",
  "Black holes",
  "Cosmic dust",
  "Celestial clouds",
  "Solar flares",
  "Lunar eclipses",
  "Celestial bodies",
  "Auroras",
  "Celestial spheres",
  "Celestial light",
};

const Set<String> zodiacSigns = {
  "Aries Sign",
  "Taurus Sign",
  "Gemini Sign",
  "Cancer Sign",
  "Leo Sign",
  "Virgo Sign",
  "Libra Sign",
  "Scorpio Sign",
  "Sagittarius Sign",
  "Capricorn Sign",
  "Aquarius Sign",
  "Pisces Sign",
};

const Set<String> planets = {
  "Mercury",
  "Venus",
  "Earth",
  "Mars",
  "Jupiter",
  "Saturn",
  "Uranus",
  "Neptune",
  "Pluto",
};

const Set<String> tarotCardDeck = {
  "The Fool Tarot Card",
  "The Magician Tarot Card",
  "The High Priestess Tarot Card",
  "The Empress Tarot Card",
  "The Emperor Tarot Card",
  "The Hierophant Tarot Card",
  "The Lovers Tarot Card",
  "The Chariot Tarot Card",
  "Strength Tarot Card",
  "The Hermit Tarot Card",
  "Wheel of Fortune Tarot Card",
  "Justice Tarot Card",
  "The Hanged Man Tarot Card",
  "Death Tarot Card",
  "Temperance Tarot Card",
  "The Devil Tarot Card",
  "The Tower Tarot Card",
  "The Star Tarot Card",
  "The Moon Tarot Card",
  "The Sun Tarot Card",
  "Judgement Tarot Card",
  "The World Tarot Card",
};

const Set<String> witchThings = {
  "Crystals",
  "Candles",
  "Herbs",
  "Incense",
  "Tarot cards",
  "Spells",
  "Moon phases",
  "Pentacle",
  "Cauldron",
  "Divination tools",
  "Runes",
  "Wands",
  "Book of Shadows",
  "Rituals",
  "Amulets",
  "Oils and potions",
  "Familiars",
  "Sabbats",
  "Sigils",
  "Ancestral magic",
};

const Set<String> flowers = {
  "Roses",
  "Lilies",
  "Sunflowers",
  "Tulips",
  "Daisies",
  "Orchids",
  "Jasmines",
  "Irises",
  "Carnations",
  "Peonies",
  "Daffodils",
  "Poppies",
  "Hydrangeas",
  "Marigolds",
  "Chrysanthemums",
  "Lavenders",
  "Gerbera Daisies",
  "Lilacs",
  "Lotuses",
  "Hibiscuses",
  "Pansies",
  "Geraniums",
  "Camellias",
  "Snapdragons",
  "Forget-Me-Nots",
  "Sweet Peas",
  "Zinnias",
  "Primroses",
  "Anemones",
  "Magnolias",
};

const Set<String> plants = {
  "Monstera deliciosa",
  "Ficus elastica",
  "Pothos",
  "Philodendron",
  "Snake Plant",
  "Spider Plant",
  "Aloe vera",
  "Peace Lily",
  "English Ivy",
  "Jade Plant",
  "Boston Fern",
  "African Violet",
  "Peperomia",
  "Chinese Money Plant",
  "Swiss Chard",
  "Rosemary",
  "Lavender",
  "Basil",
  "Mint",
  "Succulents",
  "Geraniums",
  "Marigolds",
  "Petunias",
  "Sunflowers",
  "Snapdragons",
  "Zinnias",
  "Orchids",
  "Hydrangeas",
  "Roses",
};

const Set<String> mythology = {
  "Zeus",
  "Thor's Hammer",
  "Pegasus",
  "Excalibur",
  "Medusa",
  "Amaterasu",
  "Anubis",
  "Pandora's Box",
  "Poseidon's Trident",
  "Cupid",
  "Valkyries",
  "Shiva's Third Eye",
  "Sirens",
  "Mjölnir",
  "Hades' Helm of Darkness",
  "Quetzalcoatl",
  "Leprechauns",
  "Kraken",
  "Kappa",
  "Baba Yaga",
  "Furies",
  "The Fountain of Youth",
  "Chimaera",
  "Ganesha",
  "Amun-Ra",
  "Smaug",
  "The Flying Dutchman",
  "The Minotaur",
  "The Sphinx",
  "The Loch Ness Monster",
};

const Set<String> animals = {
  "Lions",
  "Tigers",
  "Elephants",
  "Giraffes",
  "Zebras",
  "Cheetahs",
  "Gorillas",
  "Monkeys",
  "Chimpanzees",
  "Wolves",
  "Foxes",
  "Bears",
  "Deer",
  "Moose",
  "Kangaroos",
  "Koalas",
  "Pandas",
  "Dolphins",
  "Whales",
  "Sharks",
  "Octopuses",
  "Turtles",
  "Penguins",
  "Owls",
  "Eagles",
  "Parrots",
  "Peacocks",
  "Flamingos",
  "Swans",
  "Butterflies",
  "Bees",
  "Ladybugs",
  "Elephant seals",
  "Meerkats",
  "Crocodiles",
  "Camels",
  "Sloths",
  "Hedgehogs",
  "Orangutans",
  "Rhinoceroses",
  "Hippopotamuses",
  "Jellyfish",
  "Platypuses",
  "Raccoons",
  "Lemurs",
  "Squirrels",
};
