import 'dart:math';

String getQuoteTattooDescription() {
  final List<Set<String>> quoteOptions = [
    funnyQuotes,
    inspirationalQuotes,
    scaryQuotes,
    sadQuotes,
  ];

  //choose a random set from options
  final Set<String> chosenQuoteSet =
      quoteOptions[Random().nextInt(quoteOptions.length)];

  //choose a random quote from the chosen option
  final String chosenQuote =
      chosenQuoteSet.elementAt(Random().nextInt(chosenQuoteSet.length));

  //return it in description form
  return "words saying, \"$chosenQuote\"";
}

const Set<String> funnyQuotes = {
  "I'm not lazy, I'm on energy-saving mode.",
  "I'm not clumsy, it's just the floor hates me, the tables and chairs are bullies, and the walls get in my way.",
  "I love deadlines. I love the whooshing noise they make as they go by.",
  "I'm not short, I'm concentrated awesome.",
  "My bed is a magical place where I suddenly remember everything I forgot to do.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
  "I don't need a hairstylist, my pillow gives me a new hairstyle every morning.",
  "The worst time to have a heart attack is during a game of charades.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "My room isn't messy, it's an obstacle course designed to keep me fit.",
  "I tried being normal once. Worst two minutes of my life.",
  "I don't need a personal trainer, I need someone to follow me around and slap unhealthy food out of my hand.",
  "The problem with the gene pool is that there's no lifeguard.",
  "I used to think I was indecisive, but now I'm not so sure.",
  "I put my phone in airplane mode, but it's not flying!",
  "Common sense is like deodorant. The people who need it most never use it.",
  "Why be a millionaire when you can just Photoshop yourself into exotic locations?",
  "The hardest part about exercising is convincing yourself that it's time to stop watching funny cat videos.",
  "I'm not clumsy, I'm just gravitationally challenged.",
  "I'm not a complete idiot. Some parts are missing.",
  "I'm not addicted to coffee. We're just in a committed relationship.",
  "I always give 100% at work: 10% on Monday, 20% on Tuesday, 40% on Wednesday, 25% on Thursday, and 5% on Friday.",
  "I'm not lazy, I'm just highly motivated to do nothing.",
  "I'm not saying I'm Batman, but have you ever seen us in the same room together?",
  "I'm on a seafood diet. I see food, and I eat it.",
  "I thought I wanted a career. Turns out, I just wanted paychecks.",
  "I'm not a chef, but I can microwave like a pro.",
  "If there's a will, there's a relative.",
  "I don't need anger management. I need people to stop annoying me.",
  "I don't need a hairstylist, I need a magician.",
  "I'm not lazy. I'm on energy-saving mode.",
  "I'm not a baker. I just whisk it till I biscuit.",
  "I'm not clumsy. I'm just an undercover ninja.",
  "I'm not a therapist, but I can listen to your problems for a nominal fee.",
  "I don't need a personal trainer. I need someone to follow me around and slap the unhealthy food out of my hand.",
  "I'm not addicted to social media. I'm just highly sociable online.",
  "I'm not a morning person. I'm a mourning person.",
  "I'm not arguing. I'm just explaining why I'm right... repeatedly.",
  "I don't need a hairstylist. I need a magician.",
  "I'm not a morning person. I'm more of a 'coffee first, talk to me later' person.",
  "I'm not a chef. I just microwave with style.",
  "I'm not a control freak. I just know exactly how things should be done.",
};

const Set<String> inspirationalQuotes = {
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "In the middle of every difficulty lies opportunity.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't watch the clock; do what it does. Keep going.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Difficulties in life are intended to make us better, not bitter.",
  "Dream big and dare to fail.",
  "The best way to predict the future is to create it.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only impossible journey is the one you never begin.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "Success is not about the destination, it's about the journey.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
  "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Success is not in what you have, but who you are.",
  "The biggest adventure you can take is to live the life of your dreams.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Strive not to be a success, but rather to be of value.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Success is not the absence of failure; it's the persistence through failure.",
  "You are capable of more than you know. Choose a goal that seems right for you and strive to be the best, however hard the path.",
  "The road to success and the road to failure are almost exactly the same.",
};

const Set<String> scaryQuotes = {
  "Fear is the path to the dark side. Fear leads to anger, anger leads to hate, hate leads to suffering.",
  "We have nothing to fear but fear itself.",
  "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.",
  "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.",
  "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
  "It is the unknown we fear when we look upon death and darkness, nothing more.",
  "Sometimes, the things we see in the shadows are more than just shadows.",
  "The scariest monsters are the ones that lurk within our souls.",
  "Beware; for I am fearless, and therefore powerful.",
  "Fear can hold you prisoner. Hope can set you free.",
  "When there's no more room in hell, the dead will walk the earth.",
  "Do you want to know the terror of he who falls asleep? To the very toes he is terrified, because the ground gives way under him and the dream begins.",
  "We all go a little mad sometimes.",
  "The darkest places in hell are reserved for those who maintain their neutrality in times of moral crisis.",
  "What's the most you ever lost on a coin toss?",
  "They're here!",
  "All work and no play makes Jack a dull boy.",
  "He's right behind me, isn't he?",
  "I see dead people.",
  "We all float down here.",
  "I'm your number one fan.",
  "Heeeere's Johnny!",
  "They're coming to get you, Barbara!",
  "I am the devil, and I am here to do the devil's work.",
  "Be afraid. Be very afraid.",
  "It's alive! It's alive!",
  "Do you want to play a game?",
  "Listen to them. Children of the night. What music they make.",
  "Whatever you do, don't fall asleep.",
  "I'm your worst nightmare.",
  "There's no more room in hell.",
  "I'm afraid to close my eyes, I'm afraid to open them.",
  "Sometimes, dead is better.",
  "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",
  "It's not the house that's haunted. It's your son.",
  "The call is coming from inside the house!",
  "What's your favorite scary movie?",
  "We have such sights to show you.",
  "You've got red on you.",
  "They're all gonna laugh at you!",
  "One, two, Freddy's coming for you.",
  "I'm the king of the world!",
  "Don't go in the water.",
  "I am the monster in the dark. I am the beast under your bed. And I am the nightmare that wakes you up in a cold sweat.",
  "Look at me! It's all for you!",
};

const Set<String> sadQuotes = {
  "The walls we build around us to keep out the sadness also keep out the joy.",
  "The worst kind of sadness is not being able to explain why.",
  "The scars you can't see are the hardest to heal.",
  "Behind every beautiful thing, there's some kind of pain.",
  "The saddest people smile the brightest.",
  "Sometimes, it's better to be alone. Nobody can hurt you.",
  "It's sad when someone you know becomes someone you knew.",
  "I smile not because I'm happy, but because I want people to think I'm fine.",
  "The greatest pain that comes from love is loving someone you can never have.",
  "Tears come from the heart and not from the brain.",
  "It hurts to let go, but sometimes it hurts more to hold on.",
  "The worst feeling is pretending you don't care about something when it's all you seem to think about.",
  "You can close your eyes to things you don't want to see, but you can't close your heart to things you don't want to feel.",
  "The saddest summary of a life contains three descriptions: could have, might have, and should have.",
  "You flew off with the wings of my heart and left me flightless.",
  "It's sad when someone you love becomes a memory, but it's even sadder when they become a stranger.",
  "Sadness flies away on the wings of time.",
  "Sometimes, you just have to smile, pretend everything's okay, hold back the tears, and just walk away.",
  "The deeper the sorrow carves into your being, the more joy you can contain.",
  "The saddest thing about betrayal is that it never comes from your enemies; it comes from those you trust the most.",
  "I didn't want to admit it. It was easier to lie. Hide the hurt and emptiness to smile instead of cry.",
  "You can't buy love, but you can pay heavily for it.",
  "Sometimes, you have to laugh to keep from crying, and keep on moving forward.",
  "Don't cry because it's over, smile because it happened.",
  "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.",
  "Every heart has its own pain. Only the way of expressing it is different. Fools hide it in eyes, while the brilliant hide it in their smile.",
  "It hurts when you have someone in your heart but not in your arms.",
  "Sadness is but a wall between two gardens.",
  "Pain is inevitable. Suffering is optional.",
  "I'm not okay, but I smile anyway.",
  "I always knew looking back on the tears would make me laugh, but I never knew looking back on the laughs would make me cry.",
  "The only thing standing between me and total happiness is reality.",
  "I didn't know someone could love me this much until I felt the sadness in their smile when I tried to leave.",
  "Sometimes, the smallest things in life can hurt the most.",
  "It's sad when you realize you aren't as important to someone as you thought you were.",
  "Tears are words that need to be written.",
  "I miss the person I used to be.",
  "I'm not okay, but I will be.",
  "Sadness is but a part of the tapestry of life.",
  "Sometimes, you have to accept the fact that some people can only be in your heart, but not in your life.",
  "The saddest kind of sad is the sad that tries not to be sad.",
  "The hardest thing is not talking to someone you used to talk to every day.",
  "Behind my smile is a broken heart, behind my laugh I'm falling apart. Behind my eyes are tears at night, behind my body is a soul trying to fight.",
  "Sometimes, you have to let go of the one you love to find out if there is really something there.",
  "It hurts to breathe because every breath I take proves I can't live without you.",
  "The saddest thing is when you are feeling real down, you look around and realize that there is no shoulder for you.",
  "One day, you'll wake up and realize that you're no longer sad. Until then, the sadness will keep you company.",
  "It's hard to forget someone who gave you so much to remember.",
  "The saddest part in life is saying goodbye to someone you wish to spend your lifetime with.",
  "The saddest word in the whole wide world is the word 'almost'.",
  "It's sad when you realize that you aren't as important to someone as you thought you were.",
  "Sometimes, it's easier to pretend you don't care than to admit it's killing you.",
  "It's sad how people become what they had promised they never will.",
  "I'm sorry if I changed, but you changed too.",
  "You were both my lesson and my blessing.",
  "It's sad how people claim to care but ultimately leave you when you need them the most.",
  "Don't be sad because it's over, smile because it happened.",
};
