import 'package:toplife/main_systems/system_journal/constants/journal_characters.dart';
import 'package:toplife/main_systems/system_person/constants/gender.dart';
import 'package:toplife/core/data_source/drift_database/database_provider.dart';
import 'package:toplife/main_systems/system_relationship/constants/child_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/inlaw_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/parent_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/partner_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/relative_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/sibling_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/domain/model/info_models/relationship_pair.dart';

class RelationshipTestLists {
  static final childRelationship = Child(
    hidden: false,
    paternityFraud: false,
    assumedRelationshipType: JournalCharacters.emptyString,
    mainPersonId: 1,
    childId: 2,
    interestedInRelationship: true,
    currentlyLivingTogether: true,
    childRelationshipType: ChildRelationshipType.adopted.name,
    relationship: 45,
  );
  static final testChildrenList = [
    RelationshipPair(
      relationship: childRelationship.copyWith(
        childRelationshipType: ChildRelationshipType.adopted.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: childRelationship.copyWith(
        childRelationshipType: ChildRelationshipType.step.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: childRelationship.copyWith(
        childRelationshipType: ChildRelationshipType.birth.name,
        currentlyLivingTogether: false,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final exesRelationship = Partner(
    endDay: 0,
    jointMoney: 0,
    mainPersonId: 1,
    partnerId: 2,
    partnerRelationshipType: PartnerRelationshipType.casual.name,
    isActive: false,
    startDay: 34,
    isCoParent: true,
    metAt: "metAt",
    relationship: 68,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );

  static final testExesList = [
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.casual.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.casual.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.married.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.married.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
          partnerRelationshipType: PartnerRelationshipType.dating.name,
          currentlyLivingTogether: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.dating.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: exesRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static const friendRelationship = Friend(
    mainPersonId: 1,
    friendId: 2,
    metAt: "metAt",
    relationship: 66,
    haveRomanticRelationship: false,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );

  static final testFriendsList = [
    RelationshipPair(
      relationship: friendRelationship.copyWith(
        relationship: 55,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: friendRelationship.copyWith(
        relationship: 89,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: friendRelationship.copyWith(
        relationship: 23,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static const testGraves = [
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Mother",
      dayOfDeath: 45,
      fullName: "Fiona Merril",
      ageAtDeath: "Element",
    ),
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Father",
      dayOfDeath: 45,
      fullName: "Hewie Merril",
      ageAtDeath: "Element",
    ),
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Son",
      dayOfDeath: 45,
      fullName: "Jack Merril",
      ageAtDeath: "Element",
    ),
  ];

  static final inLawRelationship = InLaw(
    haveRomanticRelationship: false,
    mainPersonId: 1,
    inLawId: 2,
    likesMainPerson: true,
    inLawRelationshipType: InLawRelationshipType.sibling.name,
    relationship: 89,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );

  static final testInLawsList = [
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.sibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.child.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.child.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.child.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.parent.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.sibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.sibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: inLawRelationship.copyWith(
        inLawRelationshipType: InLawRelationshipType.parent.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final parentRelationship = Parent(
    hidden: false,
    paternityFraud: false,
    assumedRelationshipType: JournalCharacters.emptyString,
    mainPersonId: 1,
    parentId: 2,
    parentRelationshipType: ParentRelationshipType.grand.name,
    relationship: 34,
    isActive: true,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );

  static final testParentsList = [
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.grand.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.main.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.step.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.grand.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.main.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.step.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.grand.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: parentRelationship.copyWith(
        parentRelationshipType: ParentRelationshipType.step.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final partnerRelationship = Partner(
    endDay: 0,
    jointMoney: 0,
    mainPersonId: 1,
    partnerId: 2,
    partnerRelationshipType: PartnerRelationshipType.casual.name,
    isActive: false,
    startDay: 34,
    isCoParent: true,
    metAt: "metAt",
    relationship: 68,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );
  static final testPartnersList = [
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isCoParent: true,
        relationship: 90,
        isActive: true,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: partnerRelationship.copyWith(
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isCoParent: true,
        relationship: 90,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final relativesRelationship = Relative(
    mainPersonId: 1,
    relativeId: 2,
    currentlyLivingTogether: true,
    relativeRelationshipType: RelativeRelationshipType.grandchild.name,
    relationship: 56,
    interestedInRelationship: true,
  );

  static final testRelativesList = [
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.pibling.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Stella",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.cousin.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jarvis",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.pibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mark",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: relativesRelationship.copyWith(
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final siblingRelationship = Sibling(
    mainPersonId: 1,
    siblingId: 2,
    siblingRelationshipType: SiblingRelationshipType.step.name,
    relationship: 80,
    currentlyLivingTogether: false,
    interestedInRelationship: true,
  );

  static final testSiblingList = [
    RelationshipPair(
      relationship: siblingRelationship.copyWith(
        siblingRelationshipType: SiblingRelationshipType.step.name,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: siblingRelationship.copyWith(
        siblingRelationshipType: SiblingRelationshipType.full.name,
        currentlyLivingTogether: true,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: siblingRelationship.copyWith(
        siblingRelationshipType: SiblingRelationshipType.half.name,
      ),
      person: Person(
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
        hasDriversLicense: false,
      ),
    ),
  ];
}
