import 'package:toplife/main_systems/system_journal/constants/journal_characters.dart';
import 'package:toplife/main_systems/system_person/constants/gender.dart';
import 'package:toplife/core/data_source/drift_database/database_provider.dart';
import 'package:toplife/main_systems/system_relationship/constants/child_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/inlaw_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/parent_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/partner_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/relative_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/constants/sibling_relationship_type.dart';
import 'package:toplife/main_systems/system_relationship/domain/model/info_models/relationship_pair.dart';

class RelationshipTestLists {
  static final testChildrenList = [
    RelationshipPair(
      relationship: Child(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          childId: 2,
          inYourCustody: true,
          childRelationshipType: ChildRelationshipType.adopted.name,
          relationship: 45),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Child(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          childId: 2,
          inYourCustody: false,
          childRelationshipType: ChildRelationshipType.step.name,
          relationship: 45),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Child(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          childId: 2,
          inYourCustody: true,
          childRelationshipType: ChildRelationshipType.birth.name,
          relationship: 45),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testExesList = [
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testFriendsList = [
    RelationshipPair(
      relationship: const Friend(
          mainPersonId: 1,
          friendId: 2,
          metAt: "metAt",
          relationship: 66,
          haveRomanticRelationship: false),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: const Friend(
          mainPersonId: 1,
          friendId: 2,
          metAt: "metAt",
          relationship: 66,
          haveRomanticRelationship: false),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: const Friend(
          mainPersonId: 1,
          friendId: 2,
          metAt: "metAt",
          relationship: 66,
          haveRomanticRelationship: false),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static const testGraves = [
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Mother",
      dayOfDeath: 45,
      fullName: "Fiona Merril",
      ageAtDeath: "Element",
    ),
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Father",
      dayOfDeath: 45,
      fullName: "Hewie Merril",
      ageAtDeath: "Element",
    ),
    Grave(
      mainPersonId: 1,
      deadPersonId: 2,
      relationshipType: "Son",
      dayOfDeath: 45,
      fullName: "Jack Merril",
      ageAtDeath: "Element",
    ),
  ];

  static final testInLawsList = [
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.sibling.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.child.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.child.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.child.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.parent.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.sibling.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.sibling.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: InLaw(
          haveRomanticRelationship: false,
          mainPersonId: 1,
          inLawId: 2,
          likesMainPerson: true,
          inLawRelationshipType: InLawRelationshipType.parent.name,
          relationship: 89),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testParentsList = [
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.grand.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.main.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.step.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.grand.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.main.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.step.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.grand.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Parent(
          hidden: false,
          paternityFraud: false,
          assumedRelationshipType: JournalCharacters.emptyString,
          mainPersonId: 1,
          parentId: 2,
          parentRelationshipType: ParentRelationshipType.step.name,
          relationship: 34,
          isActive: true),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testPartnersList = [
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.casual.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isActive: true,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.married.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.dating.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Partner(
        endDay: 0,
        jointMoney: 0,
        mainPersonId: 1,
        partnerId: 2,
        partnerRelationshipType: PartnerRelationshipType.engaged.name,
        isActive: false,
        startDay: 34,
        isCoParent: true,
        metAt: "metAt",
        relationship: 68,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testRelativesList = [
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.pibling.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Stella",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.cousin.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jarvis",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Jim",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.pibling.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mark",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Mary",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Xavier",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.nibling.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Natalie",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Relative(
        mainPersonId: 1,
        relativeId: 2,
        inYourCustody: true,
        relativeRelationshipType: RelativeRelationshipType.grandchild.name,
        relationship: 56,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Ted",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
  ];

  static final testSiblingList = [
    RelationshipPair(
      relationship: Sibling(
        mainPersonId: 1,
        siblingId: 2,
        siblingRelationshipType: SiblingRelationshipType.step.name,
        relationship: 80,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Janet",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Sibling(
        mainPersonId: 1,
        siblingId: 2,
        siblingRelationshipType: SiblingRelationshipType.full.name,
        relationship: 57,
      ),
      person: Person(
        hasDriversLicense: false,
        id: 2,
        gameId: 2,
        firstName: "Sam",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Male.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
      ),
    ),
    RelationshipPair(
      relationship: Sibling(
        mainPersonId: 1,
        siblingId: 2,
        siblingRelationshipType: SiblingRelationshipType.half.name,
        relationship: 14,
      ),
      person: Person(
        id: 2,
        gameId: 2,
        firstName: "Cynthia",
        lastName: "Johnson",
        dayOfBirth: 34,
        gender: Gender.Female.name,
        subjectPronoun: "subjectPronoun",
        objectPronoun: "objectPronoun",
        sexuality: "sexuality",
        birthState: "Ontario",
        birthCountry: "Canada",
        currentState: "Ontario",
        currentCountry: "Canada",
        zodiacSign: "zodiacSign",
        transportMode: "bus",
        hasFertilityIssues: true,
        onBirthControl: false,
        isSterile: false,
        sickly: true,
        rebellious: false,
        dead: false,
        possessivePronoun: "possessivePronoun",
        money: 750,
        hasDriversLicense: false,
      ),
    ),
  ];
}
