class CompanyNames {
  //  medical, pharmacy, science
  static final Set<String> scienceCompanyNamesList = {
    "Brain",
    "The Grand",
    "Ace",
    "Agile One",
    "Peachy Pill",
    "Homegrown",
    "Feeling Better",
    "Academic",
    "Acute",
    "Dew Drop",
    "Healthy Holistic Heroes",
    "Hydrate and Heal",
    "Aesthetic Audit",
    "Bodacious Bioscience",
    "Charming",
    "Compassionate Care",
    "Magic",
    "Health Booster",
    "Modern Healthcare",
    "Uplift Health",
    "Wall Street",
    "Med Factory",
    "Noble Cure",
    "Med Express",
    "Cure Vibe",
    "Medical Street",
    "Cure Tablet",
    "MedSphere",
    "Healthy Elite",
    "Happy Cures",
    "Advanced Meds",
    "Rapid Cure",
    "Unicorn Health",
    "Truth",
    "Super Health",
    "Alpha",
    "Medi Bid",
    "Medibles",
    "Medical Point",
    "Medway",
    "Medicality",
    "Medallion",
    "Zoology Med Lab",
    "Medi Pride",
    "Healthcare Pathway",
    "Happy Docs",
    "Red Medicine",
    "Medi Bond",
    "MediScrutiny",
    "Blaze Health",
    "Cure Wellness",
    "Pills and Cures",
    "Healin' Care",
    "Doctor's Helping Hands",
    "Meds Ease",
    "Med Jet",
    "Med Works",
    "Ridiculously Happy Health",
    "Cure Clinic",
    "Right Lab",
    "Get Well",
    "Comprehensive",
    "MediGlow",
    "Medi Box",
    "Dr. Medica",
    "Medical Supply",
    "Regenerative",
    "Healthy Options",
    "Medi Care",
    "Lifeline",
    "Helping Hands",
    "3rd Dimension",
    "Green Cross",
    "Vitality",
    "Atlas",
    "Healing Hands",
    "Active Health",
  };

  // whiteCollar, finance, tech
  static final Set<String> corporateCompanyNamesList = {
    "Rapid",
    "Blink",
    "Logan",
    "Banktik",
    "Fodora",
    "Royal",
    "Securitas",
    "Smartly",
    "Secure",
    "Flows",
    "Borderless",
    "Enkrypt",
    "Full Fledged",
    "Full Wealth",
    "Grow Your Money",
    "The Money Wagon",
    "Fierce",
    "Budget",
    "Wise Wealth",
    "Legendary Wealth",
    "Digital",
    "Future",
    "Building Bank",
    "Fred",
    "Round Trip Wealth",
    "Your Wealth Story",
    "The Money Guru",
    "Swift",
    "City Wealth",
    "ABC Wealth",
    "Wealth Foundry",
    "Finance First",
    "Switch",
    "Ready",
    "Affirmed",
    "Wealth Navigators",
    "The Finance Advisory",
    "A+",
    "New Beginnings",
    "Smart Money",
    "Access Wealth",
    "Energy",
    "Synergist",
    "Infrared",
    "Surge",
    "Pasha Power",
    "TRUE",
    "Innovate",
    "Mode",
    "Phalanx",
    "Core",
    "Connect",
    "TurnKey",
    "Ark",
    "The Mason",
    "Fortitude",
    "Ecopad",
    "Alliance",
    "Bridgeway",
    "Altitude",
    "Matrix Markting",
    "Corpology",
  };

  // blueCollar, social work
  static final Set<String> workCompanyNamesList = {
    "Picks",
    "Metrics",
    "Bison",
    "Save",
    "Heron",
    "Brands",
    "Starlight",
    "Artemis",
    "Title",
    "Tsunami",
    "Scope",
    "Fanatic",
    "Foster",
    "Venue",
    "Dreaming",
    "Conserve",
    "ParkPlace",
    "NorthBay",
    "Nightingale",
    "Mighty",
    "Silk",
    "SouthShore",
    "Friends",
    "Charter",
    "Handy",
    "Vintage",
    "Learning",
    "Access",
    "Resonant",
    "Share",
    "Deal",
    "Scribe",
    "Myriad",
    "Lord",
    "Lion",
    "Elements",
    "First",
    "More",
    "Prince",
    "GreenValley",
    "Release",
    "Angle",
    "Tab",
    "Sell",
    "Rabbit",
    "GoodLife",
    "Season",
  };

  //sexwork
  static final Set<String> sexWorkCompanyNamesList = {
    "Bamboogles",
    "Oceanic",
    "Whisky",
    "The Blend",
    "Terra",
    "Cognita",
    "Babylonian",
    "Sphynx",
    "Zephyr",
    "Porcelain",
    "Encore",
    "Paradise",
    "Nexus",
    "Eternal",
    "Imperial",
    "Elysian",
    "Dynasty",
    "Amber",
    "Sin",
    "Matrixxx",
    "Night Beats",
    "Young and Restless",
    "The Place",
    "Feel the Beat",
    "Eclectic",
    "Hipster",
    "The Base",
    "Champagne Lux",
    "The After Party",
    "Rhythm",
    "Heart",
    "VIP",
    "Rooftop",
    "Sensations",
    "Soul Escape",
    "Utopia",
    "Soul Groove",
    "Night Craving",
    "Delirium",
  };

  // creative, communication
  static final Set<String> creativeCompanyNamesList = {
    "Spot",
    "Creations & Magic",
    "Contextual",
    "The Baroque",
    "Gentle",
    "The Creative Pod",
    "Slice Of Life",
    "Mug",
    "Stirring",
    "Mystical",
    "Reflective",
    "Essence",
    "Limitless Delights",
    "Renaissance",
    "Metal Edge",
    "The Works",
    "Techno",
    "Byzantine",
    "Peaks",
    "Primitive Creations",
    "Azan",
    "Flow Tate",
    "Allure",
    "Angel",
    "Daisy",
    "La Maison",
    "Land",
    "Madrone",
    "Park Life",
    "Wave",
    "Pinot's",
    "Urban",
    "Viberant",
    "Dash",
    "Brain",
    "Floyds",
    "Magic Ink",
    "Qurious Sasa",
    "Flembe Essence",
    "Minna Glora",
  };

  // education,
  static final Set<String> educationCompanyNamesList = {
    "Accelerated",
    "Success",
    "Meadows",
    "Winters",
    "Granite Bay",
    "Crestview",
    "Golden Oak",
    "Eagle Mountain",
    "Somerset",
    "Ravenwood",
    "New",
    "Foundations",
    "Summerfield",
    "Desert Sands",
    "Maple Ridge",
    "Cypress",
    "Champions",
    "Five Star",
    "Oakwood",
    "Westview",
    "Foothill",
  };

  // law,
  static final Set<String> lawCompanyNamesList = {
    "Crooks",
    "Ziemann - Kirlin",
    "Christiansen",
    "Frami, Boyle and Bode",
    "Wiza - Fahey",
    "Grady",
    "Ritchie",
    "Stark",
    "Morissette",
    "Leuschke",
    "Brown and Wilderman",
    "Block",
    "Wintheiser",
    "Bosco",
    "Blick and Gutmann",
    "Wiza and Rowe",
    "Hilll - Klein",
    "Wyman - Stracke",
    "Triumphus",
    "De Facto",
    "Affaires",
    "Convictus",
    "Affidavit",
    "Marston & Morgan",
    "Justice",
    "Lex Scripta",
    "Legal Capital",
    "Alliance",
    "Absolute",
    "Confident",
    "Careful",
    "Commended",
    "Correct",
    "Counsel",
    "Credible",
    "Defense",
  };

  // engineering,
  static final Set<String> engineeringCompanyNamesList = {
    "Energy",
    "Synergist",
    "Infrared",
    "Surge",
    "Pasha Power",
    "TRUE",
    "Innovate",
    "Mode",
    "Phalanx",
    "Core",
    "Connect",
    "TurnKey",
    "Ark",
    "The Mason",
    "Fortitude",
    "Ecopad",
    "Alliance",
    "Bridgeway",
    "Altitude",
    "Matrix Markting",
    "Corpology",
    "Innova",
    "Telecomm",
    "Vertigo",
    "Premier",
    "Stock",
    "Green Stone",
    "Four Rivers",
    "Herald",
    "Borderless",
    "Sylvan",
    "Lumini",
    "OptiFibre",
    "Ecohonic",
    "PURE",
    "Infinite",
    "SpaceTech",
    "Solarnet",
    "Accelerate",
    "Shift",
  };
}
